### ISSUE TITLE
anonapi 1.0.0 release checklist 

### ISSUE THREAD

**Issue by sjoerdk** [sjoerdk/anonapi#149]
anonapi has been running for a while and is being used my multiple people. Its time for a release.

- [x] Implement path-based job creation
- [x] Update docs for job creation
- [x] Review readme, update where needed
- [ ] Add entry-level pdf about installing python, launching cmd for windows users
- [x] Review docs for existing functionality

**Comment by sjoerdk** [comment]
Not including any pdf. Installation information is included in docs directly. Will see in the coming months how different types of users interact with these.
